-- Acrónimo de acuerdo al sistema
-- Nisum --> NSM

CREATE TABLE NIM_USER
(
    USR_ID           VARCHAR(36)  NOT NULL,
    USR_NAME         VARCHAR(100) NOT NULL,
    USR_EMAIL        VARCHAR(100) NOT NULL,
    USR_PASSWORD     VARCHAR(75)  NOT NULL,
    USR_STATUS       TINYINT      NOT NULL,
    USR_LAST_LOGIN   DATETIME DEFAULT CURRENT_TIMESTAMP(),
    USR_DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP(),
    USR_DATE_MODIFIED DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (USR_ID)
);

CREATE TABLE NIM_PHONE
(
    PHE_ID           VARCHAR(36)  NOT NULL,
    PHE_NUMBER       VARCHAR(15)  NOT NULL,
    PHE_CITY_CODE    INT          NOT NULL,
    PHE_COUNTRY_CODE INT          NOT NULL,
    PHE_USR_ID       VARCHAR(36),
    PHE_DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP(),
    PHE_DATE_MODIFIED DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (PHE_ID),
    FOREIGN KEY (PHE_USR_ID) REFERENCES NIM_USER (USR_ID)
);

CREATE TABLE NIM_ROL
(
    ROL_ID           VARCHAR(36)  NOT NULL,
    ROL_NAME         VARCHAR(20)  NOT NULL,
    ROL_DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP(),
    ROL_DATE_MODIFIED DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (ROL_ID)
);

CREATE TABLE NIM_USER_AND_ROLE
(
    UAR_ID           VARCHAR(36) AUTO_INCREMENT,
    UAR_USR_ID       VARCHAR(36),
    UAR_ROL_ID       VARCHAR(36),
    UAR_DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP(),
    UAR_DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (UAR_ID),
    FOREIGN KEY (UAR_USR_ID) REFERENCES NIM_USER (USR_ID),
    FOREIGN KEY (UAR_ROL_ID) REFERENCES NIM_ROL (ROL_ID)
);

